#!/bin/bash
# Bifrost Gateway Setup Script
# ============================
# Helps you configure the gateway for first-time use

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

echo "🌈 Bifrost Gateway Setup"
echo "========================"
echo ""

# Check if .env exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists at $ENV_FILE"
    read -p "Do you want to overwrite it? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file."
        exit 0
    fi
fi

echo "📝 Let's configure your Bifrost Gateway..."
echo ""

# Telegram Bot Token
echo "1. First, create a Telegram bot:"
echo "   - Open Telegram and message @BotFather"
echo "   - Send /newbot and follow the prompts"
echo "   - Copy the bot token"
echo ""
read -p "Enter your Telegram Bot Token: " BOT_TOKEN

# Webhook Secret
echo ""
echo "2. Generating a webhook secret..."
WEBHOOK_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || openssl rand -base64 32 | tr -d '/+=' | head -c 32)
echo "   Generated: $WEBHOOK_SECRET"

# User ID
echo ""
echo "3. Get your Telegram user ID:"
echo "   - Message @userinfobot on Telegram"
echo "   - It will reply with your user ID"
echo ""
read -p "Enter your Telegram User ID (or press Enter to allow all users): " USER_ID

# Internal service URLs
echo ""
echo "4. Internal service configuration (press Enter for defaults):"
read -p "Norns API URL [http://gitlab-sre-hlidskjalf:8900]: " NORNS_API
NORNS_API=${NORNS_API:-http://gitlab-sre-hlidskjalf:8900}

read -p "LangGraph URL [http://gitlab-sre-langgraph:2024]: " LANGGRAPH_URL  
LANGGRAPH_URL=${LANGGRAPH_URL:-http://gitlab-sre-langgraph:2024}

read -p "Use LangGraph API? [Y/n]: " USE_LG
if [[ $USE_LG =~ ^[Nn]$ ]]; then
    USE_LANGGRAPH="false"
else
    USE_LANGGRAPH="true"
fi

read -p "Redis URL [redis://gitlab-sre-redis:6379/3]: " REDIS
REDIS=${REDIS:-redis://gitlab-sre-redis:6379/3}

# Write .env file
cat > "$ENV_FILE" << EOF
# Bifrost Gateway Configuration
# Generated by setup.sh on $(date)

# Service
APP_ENV=development
DEBUG=false

# Telegram
TELEGRAM_BOT_TOKEN=$BOT_TOKEN
TELEGRAM_WEBHOOK_SECRET=$WEBHOOK_SECRET
TELEGRAM_ALLOWED_USERS=$USER_ID

# Internal Services
NORNS_API_URL=$NORNS_API
NORNS_LANGGRAPH_URL=$LANGGRAPH_URL
USE_LANGGRAPH=$USE_LANGGRAPH
REDIS_URL=$REDIS

# Rate Limiting
RATE_LIMIT_MESSAGES=30
RATE_LIMIT_WINDOW=60
EOF

echo ""
echo "✅ Configuration saved to $ENV_FILE"
echo ""
echo "Next steps:"
echo "1. Start the gateway: docker-compose up -d"
echo "2. Expose to internet: ngrok http 8050"
echo "3. Set webhook: curl -X POST 'http://localhost:8050/webhook/set?url=https://YOUR_NGROK_URL/webhook/telegram/$WEBHOOK_SECRET'"
echo "4. Message your bot on Telegram!"
echo ""
echo "🌉 May your bridge to Asgard be strong!"

