#!/usr/bin/env bash
set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This helper only supports macOS hosts (Apple Silicon)." >&2
  exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
  echo "Homebrew is required. Install it from https://brew.sh/ first." >&2
  exit 1
fi

if ! command -v ollama >/dev/null 2>&1; then
  echo "Installing Ollama via Homebrew..."
  brew install ollama
fi

CONFIG_DIR="${HOME}/.ollama"
CONFIG_FILE="${CONFIG_DIR}/config"
mkdir -p "${CONFIG_DIR}"

cat > "${CONFIG_FILE}" <<'EOF'
# Generated by scripts/setup-host-ollama.sh
# Listen on all interfaces so Docker containers can reach the host instance.
ListenHost = "0.0.0.0"
Port = "11434"
EOF

echo "Wrote ${CONFIG_FILE} (listening on 0.0.0.0:11434)."

if launchctl list | grep -q com.ollama.launcher; then
  echo "Restarting the Ollama launchd service..."
  sudo launchctl unload -w /Library/LaunchDaemons/com.ollama.launcher.plist >/dev/null 2>&1 || true
  sudo launchctl load -w /Library/LaunchDaemons/com.ollama.launcher.plist
else
  echo "Starting Ollama in the foreground..."
  ollama serve >/tmp/ollama.log 2>&1 &
  disown
fi

echo "Done. Verify with: curl -s http://localhost:11434/api/tags | jq"

